samples/pagseguro/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url

from samples.pagseguro.views import PagSeguroDemoView, ThankYouView, CancelarAssinaturaView


urlpatterns = [
    url(r'^demo/$', PagSeguroDemoView.as_view(), name='demo'),
    url(r'^obrigado/$', ThankYouView.as_view(), name='thankyou'),
    url(r'^cancelar/(?P<pk>\d+)/$', CancelarAssinaturaView.as_view(), name='cancelar'),
]

samples/urls.py
# -*- coding: utf-8 -*-


from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^pagseguro/', include('pagseguro.urls', namespace='pagseguro')),
]

samples/pagseguro/views.py
# -*- coding: utf-8 -*-


from django.conf import settings
from django.contrib import messages
from django.urls.base import reverse_lazy
from django.views.generic import TemplateView

from platforms.pagseguro.api.api import search_transaction_by_code
from platforms.pagseguro.django.mixins import PaymentAndPreApprovalMixin, TransactionMixin, TransactionFromReferenceMixin, SubscriptionCancelView


class PagSeguroDemoView(PaymentAndPreApprovalMixin, TransactionFromReferenceMixin, TemplateView):
    u""" Mostra os botões de integração com PagSeguro e um campo para busca de uma transação. """

    template_name = 'demo.html'

    payment_code = settings.PAGSEGURO_CODE_PAYMENT
    pre_approval_code = settings.PAGSEGURO_CODE_PRE_APPROVAL

    transaction_details = None

    def post(self, request, *args, **kwargs):
        transaction = request.POST.get('transaction')
        if transaction:
            self.transaction_details = search_transaction_by_code(transaction).xml
        return super(PagSeguroDemoView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context_data = super(PagSeguroDemoView, self).get_context_data(**kwargs)
        context_data['transaction_details'] = self.transaction_details
        context_data['subscription_pk'] = 20
        return context_data


class ThankYouView(TransactionMixin, TemplateView):
    u""" View de redirecionamento após um pagamento, apenas mostra as informações do pagamento concluído. """

    template_name = 'thankyou.html'

    transaction_url_query = 'transaction_id'


class CancelarAssinaturaView(SubscriptionCancelView):
    u""" Mostra o cancelamento de uma assinatura. """

    template_name = 'cancelar.html'
    success_url = reverse_lazy('pagseguro:demo')

    def on_canceled(self):
        u""" Adicionamos uma mensagem de sucesso. """
        messages.success(self.request, u"Cancelado com sucesso.")
        return super(CancelarAssinaturaView, self).on_canceled()

    def on_not_canceled(self):
        u""" Adicionamos uma mensagem de erro. """
        messages.error(self.request, u"Não conseguiu cancelar.")
        return super(CancelarAssinaturaView, self).on_not_canceled()

samples/pagseguro/templates/cancelar.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PagSeguro Cancelamento de Assinatura</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  <p>Você tem certeza que deseja cancelar a assinatura "{{ object }}"?</p>
  <p><a href="{% url "pagseguro:demo" %}" role="button">Cancelar</a> <input type="submit" value="Confirmar" role="button"/></p>
</form>
</body>
</html>

samples/pagseguro/templates/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>PagSeguro Demo</title>
</head>
<body>
<a href="{% url 'home' %}">Voltar</a>
<br>
<br>
<b>Pagamento com Lightbox</b>
{% include "pagseguro/button/lightbox/payment.html" %}
<br>
<b>Pagamento com redirecionamento</b>
{% include "pagseguro/button/default/payment.html" %}
<br>
<b>Assinatura de recorrência com redirecionamento</b>
{% include "pagseguro/button/default/pre-approval.html" %}
<br>
<b>Buscar informações de transação</b>
<form action="" method="get">
  <input type="text" name="transaction" placeholder="FC309EF446FA42118B4F8413D56F56E8" style="height: 24px; width: 256px;">
  <button type="submit" style="height: 28px;">Buscar</button>
</form>
{% if transaction %}
  <h5>Transação Encontrada:</h5> {{ transaction.code }}
{% endif %}
<br>
<b>Cancelamento de assinatura</b>
{% if messages %}
  <ul>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}
<a href="{% url 'pagseguro:cancelar' subscription_pk %}">Cancelar</a>
</body>
</html>

samples/pagseguro/templates/thankyou.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Thank You!</title>
</head>
<body>
<a href="{% url "home" %}">Voltar</a>
<br>
<br>
{% if transaction %}
  Obrigado pela compra!
  <br>
  {{ transaction }}
{% else %}
  Ops! Compra não encontrada...
{% endif %}
</body>
</html>

samples/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Samples</title>
</head>
<body>
<h3>Samples de Plataformas de Pagamento</h3>
<ul>
  <li><a href="{% url "pagseguro:demo" %}">PagSeguro</a></li>
</ul>
</body>
</html>